"""update trial display

Revision ID: 24e1c88a8830
Revises: 
Create Date: 2026-04-13 17:54:14.102981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24e1c88a8830'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vpn_accesses_user_id'), table_name='vpn_accesses')
    op.drop_table('vpn_accesses')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'traffic_used',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_column('users', 'terms_accepted')
    op.drop_column('users', 'terms_accepted_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'access_type')
    op.drop_column('users', 'subscription_expiry')
    op.drop_column('users', 'language')
    op.drop_column('users', 'telegram_id')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'traffic_limit')
    op.drop_column('users', 'trial_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('trial_used', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('traffic_limit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('subscription_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('access_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('terms_accepted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('terms_accepted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.alter_column('users', 'traffic_used',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('vpn_accesses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('server_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('client_uuid', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('config_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('vpn_accesses_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('vpn_accesses_pkey'))
    )
    op.create_index(op.f('ix_vpn_accesses_user_id'), 'vpn_accesses', ['user_id'], unique=False)
    # ### end Alembic commands ###
