"""add missing columns to users

Revision ID: 5c41b5a9e69e
Revises: 24e1c88a8830
Create Date: 2026-04-13 18:07:50.330953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c41b5a9e69e'
down_revision: Union[str, None] = '24e1c88a8830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('trial_used', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('terms_accepted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('subscription_expiry', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'subscription_expiry')
    op.drop_column('users', 'terms_accepted')
    op.drop_column('users', 'trial_used')
    # ### end Alembic commands ###
