"""Initial migration

Revision ID: 8bd2a3cdc9f5
Revises: 5c41b5a9e69e
Create Date: 2026-04-13 19:10:31.146937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bd2a3cdc9f5'
down_revision: Union[str, None] = '5c41b5a9e69e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vpn_accesses_user_id'), table_name='vpn_accesses')
    op.drop_table('vpn_accesses')
    op.drop_column('users', 'access_type')
    op.drop_column('users', 'terms_accepted_at')
    op.drop_column('users', 'telegram_id')
    op.drop_column('users', 'language')
    op.drop_column('users', 'traffic_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('traffic_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('terms_accepted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('access_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('vpn_accesses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('server_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('client_uuid', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('config_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('vpn_accesses_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vpn_accesses_pkey'))
    )
    op.create_index(op.f('ix_vpn_accesses_user_id'), 'vpn_accesses', ['user_id'], unique=False)
    # ### end Alembic commands ###
