texts = {
    "ru": {
        "not_found": "Пользователь не найден",
        "error": "Произошла ошибка. Попробуйте позже.",
        "access_paid": "Активен 👑",
        "access_free": "Бесплатный ⚡",
        "access_type_free": "Бесплатный",
        "access_type_paid": "Платный",
        "access_type_none": "Отсутствует",
        "no_access": "У вас нет доступа.",
        "access_ready": "Подключение готово ✅\n\n{config}",
        "buy": "Подписка успешно активирована ✅",
    },
    "en": {
        "not_found": "User not found",
        "error": "An error occurred. Please try again later.",
        "access_paid": "Active 👑",
        "access_free": "Free ⚡",
        "access_type_free": "Free",
        "access_type_paid": "Paid",
        "access_type_none": "None",
        "no_access": "You don't have access.",
        "access_ready": "Connection is ready ✅\n\n{config}",
        "buy": "Subscription activated successfully ✅",
    },
}
